- name: installing packages
  apt:
    name={{ item }}
    state=present
  when: (ansible_os_family == "Debian")
  with_items: '{{vsftpd.packages}}'
  tags:
    - ftp

- name: installing packages
  yum:
    name={{ item }}
    state=present
  when: (ansible_os_family == "RedHat")
  with_items: '{{vsftpd.packages}}'
  tags:
    - ftp