# Old versions of OS use "service" for start|stop|etc services.
- name: Stopping service
  service:
    name={{ vsftpd.service }}
    state=stopped
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6") or (ansible_distribution == "Debian" and ansible_distribution_major_version == "7") or (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14")
  tags:
    - ftp

# Current versions of OS use "systemd" for start|stop|etc services.
- name: Stopping service
  systemd:
    name={{ vsftpd.service }}
    state=stopped
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version >= "7") or (ansible_distribution == "Debian" and ansible_distribution_major_version >= "8") or (ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "16")
  tags:
    - ftp

- name: loading configurations
  template:
    src={{ item }}.j2
    dest={{ vsftpd.conf_path }}/{{ item }}
  with_items:
    - "vsftpd.conf"
    - "vsftpd.user_list"
  tags:
    - ftp
