---

- name: Common
  hosts: all
  become: true
  become_method: sudo
  roles:
    - common
    - fail2ban
    - logrotate/common

- name: Application
  hosts: app
  become: true
  become_method: sudo
  roles:
    - deploy
    - apache/common
    - postfix
    - ftp

- name: Frontend
  hosts: fe
  become: true
  become_method: sudo
  roles:
    - nginx/proxy

- name: Databases
  hosts: db
  become: true
  become_method: sudo
  roles:
    - mysql/common

- name: NoSQL
  hosts: nosql
  become: true
  become_method: sudo
  roles:
    - redis

- name: Deploy store
  hosts: app
  become: true
  become_method: sudo
  roles:
    - cscart