---

#Adding REPO
- name: Add Varnish apt key.
  apt_key: 
    url: https://packagecloud.io/varnishcache/varnish{{ varnish.version }}/gpgkey 
    state: present

- name: Add Varnish apt repository
  apt_repository:
    repo={{ item }}
    state=present
  with_items:
    - "deb-src https://packagecloud.io/varnishcache/varnish{{ varnish.version }}/ubuntu/ trusty main"
    - "deb https://packagecloud.io/varnishcache/varnish{{ varnish.version }}/ubuntu/ trusty main"
    
# Installing packages    
- name: Install Varnish.
  apt: 
    name: "{{ varnish.package }}" 
    state: present

#Preparation configutations
#For Ubuntu 14
- name: Copy Varnish configuration.
  template:
    src: varnish.j2
    dest: /etc/default/varnish
    owner: root
    group: root
    mode: 0755
  when: ansible_distribution_major_version|int < 16

#For Ubuntu 16 and higher
- name: Copy Varnish configuration (systemd).
  template:
    src: "{{ varnish.default_params_path }}"
    dest: "{{ varnish.config_path }}/varnish.params"
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_major_version|int >= 16