---
- name: Add Varnish apt key.
  apt_key: 
    url: https://packagecloud.io/varnishcache/varnish{{ varnish.version }}/gpgkey 
    state: present

- name: Add Varnish apt repository (1/2)
  apt_repository:
    repo: "deb https://packagecloud.io/varnishcache/varnish{{ varnish.version }}/ubuntu/ trusty main"
    state: present

- name: Add Varnish apt repository (2/2)
  apt_repository:
    repo: "deb-src https://packagecloud.io/varnishcache/varnish{{ varnish.version }}/ubuntu/ trusty main"
    state: present

- name: Install Varnish.
  apt: 
    name: varnish 
    state: present

- name: Copy Varnish configuration.
  template:
    src: varnish.j2
    dest: /etc/default/varnish
    owner: root
    group: root
    mode: 0755

- name: Copy Varnish systemd configuration.
  template:
    src: varnish.service.j2
    dest: /etc/systemd/system/varnish.service
    owner: root
    group: root
    mode: 0755
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "15"
