---
- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure Varnish config path exists.
  file:
    path: "{{ varnish.config_path }}"
    state: directory

- name: Copy Varnish default VCL.
  template:
    src: "{{ varnish.default_vcl_template_path }}"
    dest: "{{ varnish.config_path }}/default.vcl"
    owner: root
    group: root
    mode: 0644
  when: varnish.use_default_vcl
  notify: restart varnish

# Old versions of OS use "service" for start|stop|etc services.
- name: putting into autostart
  service:
    name=varnish
    state=started
    enabled=yes
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6") or (ansible_distribution == "Debian" and ansible_distribution_major_version == "7") or (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14")

# Current versions of OS use "systemd" for start|stop|etc services.
- name: putting into autostart
  systemd:
    name=varnish
    state=started
    enabled=yes
    masked=no
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version >= "7") or (ansible_distribution == "Debian" and ansible_distribution_major_version >= "8") or (ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "16")