---

#Adding REPO
- name: Add Varnish repository for Centos 1/2.
  yum_repository:  
    name: varnishcache_varnish{{ varnish.version }}
    description: Varnish YUM repo 1
    file: varnish-{{ varnish.version }}
    baseurl: https://packagecloud.io/varnishcache/varnish{{ varnish.version }}/el/{{ ansible_distribution_major_version }}/$basearch
    repo_gpgcheck: yes
    gpgcheck: no
    enabled: yes
    gpgkey: https://packagecloud.io/varnishcache/varnish{{ varnish.version }}/gpgkey
    sslverify: yes
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    metadata_expire: 300
  tags:
    - varnish

- name: Add Varnish repository for Centos 2/2.
  yum_repository:  
    name: varnishcache_varnish{{ varnish.version }}-source
    description: Varnish YUM repo 2
    file: varnish-{{ varnish.version }}
    baseurl: https://packagecloud.io/varnishcache/varnish{{ varnish.version }}/el/{{ ansible_distribution_major_version }}/SRPMS
    repo_gpgcheck: yes
    gpgcheck: no
    enabled: yes
    gpgkey: https://packagecloud.io/varnishcache/varnish{{ varnish.version }}/gpgkey
    sslverify: yes
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    metadata_expire: 300
  register: setup_varnish_repo
  tags:
    - varnish

- name: Make cache
  command: "yum -q makecache -y --disablerepo='*' --enablerepo='varnishcache_varnish{{ varnish.version }}*'"
  when: setup_varnish_repo.changed
  tags:
    - varnish

# Installing packages
- name: Installing dependency for varnish.
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - jemalloc
    - redhat-rpm-config
  tags:
    - varnish

- name: Install Varnish.
  yum:
    name: "{{ varnish.package }}"
    state: present
    enablerepo: "varnishcache_varnish{{ varnish.version }}"
    disablerepo: "*"
  tags:
    - varnish

#Preparation configutations
#For CentOS 7 and higher
- name: Copy Varnish configuration (systemd).
  template:
    src: "{{ varnish.default_params_path }}"
    dest: "{{ varnish.config_path }}/varnish.params"
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_major_version|int >= 7
  tags:
    - varnish