---

- name: Installing dependency for varnish.
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - jemalloc

- name: Add Varnish repository for Centos 1/1.
  yum_repository:  
    name: varnishcache_varnish{{ varnish.version }}
    description: Varnish YUM repo 1
    file: varnish-{{ varnish.version }}
    baseurl: https://packagecloud.io/varnishcache/varnish{{ varnish.version }}/el/{{ ansible_distribution_major_version }}/$basearch
    repo_gpgcheck: yes
    gpgcheck: no
    enabled: yes
    gpgkey: https://packagecloud.io/varnishcache/varnish{{ varnish.version }}/gpgkey
    sslverify: yes
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    metadata_expire: 300

- name: Add Varnish repository for Centos 1/2.
  yum_repository:  
    name: varnishcache_varnish{{ varnish.version }}
    description: Varnish YUM repo 2
    file: varnish-{{ varnish.version }}
    baseurl: https://packagecloud.io/varnishcache/varnish{{ varnish.version }}/el/{{ ansible_distribution_major_version }}/SRPMS
    repo_gpgcheck: yes
    gpgcheck: no
    enabled: yes
    gpgkey: https://packagecloud.io/varnishcache/varnish{{ varnish.version }}/gpgkey
    sslverify: yes
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    metadata_expire: 300
  register: setup_varnish_repo

- name: Make cache
  command: "yum -q makecache -y --disablerepo='*' --enablerepo='varnishcache_varnish{{ varnish.version }}'"
  when: setup_varnish_repo.changed

- name: Installing common packages via yum.
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - redhat-rpm-config

- name: Install Varnish.
  yum:
    name: varnish
    state: present
    enablerepo: "varnishcache_varnish{{ varnish.version }}"
    disablerepo: "*"

- name: Copy Varnish configuration (sysvinit).
  template:
    src: varnish.j2
    dest: /etc/sysconfig/varnish
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_major_version|int < 7

- name: Copy Varnish configuration (systemd).
  template:
    src: varnish.params.j2
    dest: /etc/varnish/varnish.params
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_major_version|int >= 7
