---
- name: Ensure gcc is installed (Varnish dependency).
  yum: name=gcc state=present

- name: Add Varnish repository for Centos 6.
  yum:
    name: https://packagecloud.io/varnishcache/varnish40/packages/el/6/varnish-release-{{ varnish.version }}-5.el6.noarch.rpm/download.rpm
    state: present
  when: ansible_distribution_major_version|int < 7

- name: Add Varnish repository for Centos 7.
  yum:
    name: https://packagecloud.io/varnishcache/varnish40/packages/el/7/varnish-release-{{ varnish.version }}-4.el7.noarch.rpm/download.rpm
    state: present
  when: ansible_distribution_major_version|int >= 7

- name: installing common packages via yum
  yum: 
    name: {{ item }} 
    state: present
  with_items:
    - redhat-rpm-config
  when: ansible_os_family == "RedHat"

- name: installing depends for varnish
  yum: 
    name: jemalloc
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Varnish.
  yum:
    name: varnish
    state: present
    enablerepo: "varnishcache_varnish40"
    disablerepo: "*"

- name: Copy Varnish configuration (sysvinit).
  template:
    src: varnish.j2
    dest: /etc/sysconfig/varnish
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_major_version|int < 7

- name: Copy Varnish configuration (systemd).
  template:
    src: varnish.params.j2
    dest: /etc/varnish/varnish.params
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_major_version|int >= 7
