---
- name: Ensure gcc is installed (Varnish dependency).
  yum: name=gcc state=present

- name: Add Varnish repository for Centos 6.
  command:
    rpm --nosignature -i https://packagecloud.io/varnishcache/varnish40/packages/el/6/varnish-release-{{ varnish.version }}-5.el6.noarch.rpm/download.rpm
    creates=/var/lib/yum/repos/x86_64/{{ ansible_distribution_major_version|int }}/varnish-{{ varnish.version }}
  when: ansible_distribution_major_version|int < 7

- name: Add Varnish repository for Centos 7.
  command:
    rpm --nosignature -i https://packagecloud.io/varnishcache/varnish40/packages/el/7/varnish-release-{{ varnish.version }}-4.el7.noarch.rpm/download.rpm
    creates=/var/lib/yum/repos/x86_64/{{ ansible_distribution_major_version|int }}/varnish-{{ varnish.version }}
  when: ansible_distribution_major_version|int >= 7

- name: installing common packages via yum
  yum: 
    name=jemalloc
    state=present
  when: ansible_os_family == "RedHat"

- name: Install Varnish.
  yum:
    name: varnish
    state: present
    enablerepo: "varnishcache_varnish40"
    disablerepo: "*"

- name: Copy Varnish configuration (sysvinit).
  template:
    src: varnish.j2
    dest: /etc/sysconfig/varnish
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_major_version|int < 7

- name: Copy Varnish configuration (systemd).
  template:
    src: varnish.params.j2
    dest: /etc/varnish/varnish.params
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_major_version|int >= 7
