- name: installing mod_php
  apt: 
    name=libapache2-mod-php5.6 
    state=installed 
    update_cache=yes
  when: ansible_os_family == "Debian"

- name: installing mod_php
  yum: 
    name=mod_php enablerepo=remi,remi-php56 
    state=installed
  when: ansible_os_family == "RedHat"