- name: loading configs
  template:
    src={{ item }}.j2
    dest=/etc/nginx/{{ item }}
  with_items:
    - "xtra/proxy_params.conf"
    - "xtra/proxy_params_ssl.conf"
    - "conf-available/upstream.conf"
  tags:
    - nginx

- name: enabling configs
  file:
    src=/etc/nginx/conf-available/{{ item }}
    dest=/etc/nginx/conf-enabled/{{ item }}
    state=link
  with_items:
    - upstream.conf
  tags:
    - nginx

- name: loading vhosts
  template:
    src=sites-available/default.conf.j2
    dest=/etc/nginx/sites-available/{{ item.key }}.conf
  with_dict: '{{stores}}'
  tags:
    - nginx

- name: enabling vhosts
  file:
    src=/etc/nginx/sites-available/{{ item.key }}.conf
    dest=/etc/nginx/sites-enabled/{{ item.key }}.conf
    state=link
  with_dict: '{{stores}}'
  tags:
    - nginx

# Restarting NGINX
- name: Stopping service
  service:
    name={{ nginx_role.service }}
    state=restarted
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6") or (ansible_distribution == "Debian" and ansible_distribution_major_version == "7") or (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14")
  tags:
    - nginx

- name: Stopping service
  systemd:
    name={{ nginx_role.service }}
    state=restarted
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version >= "7") or (ansible_distribution == "Debian" and ansible_distribution_major_version >= "8") or (ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "16")
  tags:
    - nginx