---

- name: installing packages
  yum:
    name={{ item }}
    state=present
  with_items: '{{fail2ban_role.packages}}'
  when: ansible_os_family == "RedHat"
  tags:
    - firewall

- name: installing packages
  apt:
    name={{ item }}
    state=present
  with_items: '{{fail2ban_role.packages}}'
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"
  tags:
    - firewall

- name: loading configurations
  template:
    src={{ item }}.j2
    dest={{ fail2ban_role.path }}/{{ item }}
    mode=644
    owner=root
    group=root
  with_items:
    - jail.local
  tags:
    - firewall