#Prepare configuration
- name: deploying configuration
  template: 
    src=my.cnf.j2 
    dest={{ mysql_role.confdir }}/my.cnf 
    owner=root 
    mode=0644
    backup=yes
  tags:
    - mysql

# Old versions of OS use "service" for start|stop|etc services.
- name: putting into autostart
  service:
    name={{ mysql_role.service }}
    enabled=yes
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6") or (ansible_distribution == "Debian" and ansible_distribution_major_version == "7") or (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14")
  tags:
    - mysql

- name: restarting service
  service:
    name={{ mysql_role.service }}
    state=restarted
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6") or (ansible_distribution == "Debian" and ansible_distribution_major_version == "7") or (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14")
  tags:
    - mysql

# Current versions of OS use "systemd" for start|stop|etc services.
- name: putting into autostart
  systemd:
    name={{ mysql_role.service }}
    enabled=yes
    masked=no
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version >= "7") or (ansible_distribution == "Debian" and ansible_distribution_major_version >= "8") or (ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "16")
  tags:
    - mysql

- name: restarting service
  systemd:
    name={{ mysql_role.service }}
    state=restarted
    daemon_reload=yes
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version >= "7") or (ansible_distribution == "Debian" and ansible_distribution_major_version >= "8") or (ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= "16")
  tags:
    - mysql