#Preconf Mysql Password for Ubuntu and Debian
- name: checking for previous installation
  stat: path=/usr/sbin/mysqld
  register: mysqld_stat

- name: preseeding MySQL file
  template: 
    src: preseed.j2 
    dest: /root/mysql.seed
  when: ansible_os_family == "Debian" and mysqld_stat.stat.exists == False

- command: /usr/bin/debconf-set-selections /root/mysql.seed
  when: ansible_os_family == "Debian" and mysqld_stat.stat.exists == False

#Installing Mysql
  #APT
- name: Install a Mysql 5.7 REPO package.
  apt:
    name={{ item }}
    state=present
  with_items: '{{mysql_role.repo}}'
  when: ansible_os_family == "Debian"
  tags:
    - mysql

- name: installing dependencies via apt
  apt: 
    name={{ item }} 
    state=present
  with_items: '{{mysql_role.packages}}'
  when: ansible_os_family == "Debian"
  tags:
    - mysql

- name: installing MySQL packages via apt
  apt: 
    name={{ item }} 
    state=present
  with_items: '{{mysql_role.packages}}'
  when: ansible_os_family == "Debian"
  tags:
    - mysql

  # YUM
- name: Add Some repo
  yum:
    name={{ item }} 
    state=present
  with_items: '{{mysql_role.repo}}'
  when: ansible_os_family == "RedHat"
  tags:
    - mysql

- name: installing dependencies via yum
  yum:
    name={{ item }}
    state=present
  with_items: '{{mysql_role.dependences}}'
  when: ansible_os_family == "RedHat"
  tags:
    - mysql

- name: installing MySQL packages via yum
  yum: 
    name={{ item }} 
    state=present  
  with_items: '{{mysql_role.packages}}'
  when: ansible_os_family == "RedHat"
  tags:
    - mysql

#Prepare configuration
- name: backuping configuration
  copy:
    src={{ mysql_role.confdir }}/my.cnf 
    dest={{ mysql_role.confdir }}/my.cnf.orig
  tags:
    - mysql

- name: deploying configuration
  template: 
    src=my.cnf.j2 
    dest={{ mysql_role.confdir }}/my.cnf 
    owner=root 
    mode=0644
    backup=yes
  tags:
    - mysql