mysql_role:
  def_log: /var/log/mysqld.log
  confdir: "/etc"
  socket: "/var/lib/mysql/mysql.sock"
  repo: https://dev.mysql.com/get/mysql57-community-release-el{{ ansible_distribution_major_version }}-11.noarch.rpm
  service: mysqld
  dependences: MySQL-python
  packages:
    - mysql-server